# Site settings
author: Elliott Vargo
title: Day by Day
header-img: img/home-bg.png
email: vargoelliott@gmail.com
copyright_name: Elliott Vargo
description: > # this means to ignore newlines until "baseurl:"
  Attending Flatiron School while working in construction.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  E-Vargo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
